---
web:
  build: .
  working_dir: /usr/app
  volumes:
    - .:/usr/app
  ports:
    - '80:4567'
  environment:
    - PATH_TO_PDFTK=/usr/bin/pdftk
  restart: always
  # command: bundle exec thin start -p 4567
  command: bundle exec thin start -p 4567
